import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Matt',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Nav',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: '1',
      name: 'Astral Radiance Booster Box',
      slug: 'Astral-booster-box',
      category: 'Astral Radiance',
      image: '/images/p1.jpg',
      price: 169,
      countInStock: 1,
      brand: 'Pokemon',
      rating: 5,
      numReviews: 10,
      description: 'New Pokemon Booster Box',
    },
    {
      //_id: '2',
      name: 'Brilliant Stars Booster Box',
      slug: 'Brilliant-booster-box',
      category: 'Brilliant Stars',
      image: '/images/p2.jpg',
      price: 180,
      countInStock: 10,
      brand: 'Pokemon',
      rating: 5,
      numReviews: 30,
      description: 'New Pokemon Booster Box',
    },
    {
      // _id: '3',
      name: 'Fusion Strike Booster Box',
      slug: 'Fusion-booster-box',
      category: 'Fusion Strike',
      image: '/images/p3.jpg',
      price: 150,
      countInStock: 5,
      brand: 'Pokemon',
      rating: 3.5,
      numReviews: 15,
      description: 'New Pokemon Booster Box',
    },
    {
      //_id: '4',
      name: 'Evolving Skies Booster Box',
      slug: 'Evolving-booster-box',
      category: 'Evolving Skies',
      image: '/images/p4.jpg',
      price: 190,
      countInStock: 12,
      brand: 'Pokemon',
      rating: 4,
      numReviews: 6,
      description: 'New Pokemon Booster Box',
    },
    {
      //_id: '5',
      name: 'Battle Styles Booster Box',
      slug: 'Battle-booster-box',
      category: 'Battle Styles',
      image: '/images/p5.jpg',
      price: 155,
      countInStock: 24,
      brand: 'Pokemon',
      rating: 3,
      numReviews: 5,
      description: 'New Pokemon Booster Box',
    },
    {
      //_id: '6',
      name: '1999 Base Set Booster Box',
      slug: 'Base-booster-box',
      category: 'Base Set',
      image: '/images/p6.jpg',
      price: 2000,
      countInStock: 1,
      brand: 'Pokemon',
      rating: 5,
      numReviews: 1,
      description: '1999 Pokemon Booster Box',
    },
    {
      //_id: '7',
      name: 'Sword & Shield Booster Box',
      slug: 'Sword-booster-box',
      category: 'Sword & Shield',
      image: '/images/p7.jpg',
      price: 325,
      countInStock: 10,
      brand: 'Pokemon',
      rating: 3.5,
      numReviews: 55,
      description: 'New Pokemon Booster Box',
    },
    {
      //_id: '8',
      name: 'Darkness Ablaze Booster Box',
      slug: 'Darkness-booster-box',
      category: 'Darkness Ablaze',
      image: '/images/p8.jpg',
      price: 210,
      countInStock: 50,
      brand: 'Pokemon',
      rating: 4.5,
      numReviews: 22,
      description: 'New Pokemon Booster Box',
    },
  ],
};

export default data;
