const data = {
  products: [
    {
      name: 'Astral Radiance Booster Box',
      slug: 'Astral-booster-box',
      category: 'Astral Radiance',
      image: '/images/.jpg',
      price: 169,
      countInStock: 1,
      Brand: 'Pokemon',
      rating: 5,
      numReviews: 10,
      description: 'New Pokemon Booster Box',
    },
    {
      name: 'Brilliant Stars Booster Box',
      slug: 'Brilliant-booster-box',
      category: 'Brilliant Stars',
      image: '/images/.jpg',
      price: 180,
      countInStock: 10,
      Brand: 'Pokemon',
      rating: 5,
      numReviews: 30,
      description: 'New Pokemon Booster Box',
    },
    {
      name: 'Fusion Strike Booster Box',
      slug: 'Fusion-booster-box',
      category: 'Fusion Strike',
      image: '/images/.jpg',
      price: 150,
      countInStock: 5,
      Brand: 'Pokemon',
      rating: 3.5,
      numReviews: 15,
      description: 'New Pokemon Booster Box',
    },
    {
      name: 'Evolving Skies Booster Box',
      slug: 'Evolving-booster-box',
      category: 'Evolving Skies',
      image: '/images/.jpg',
      price: 190,
      countInStock: 12,
      Brand: 'Pokemon',
      rating: 4,
      numReviews: 6,
      description: 'New Pokemon Booster Box',
    },
  ],
};
